version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pwd}
      POSTGRES_DB: ${POSTGRES_DB:-pg}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - api-network

  api:
    restart: always
    build:
      context: ./server
    command: /bin/bash -c "while sleep 1000; do :; done"
    working_dir: /usr/src/app
    networks:
      - api-network
    volumes:
      - ./:/usr/src/app:cached
    depends_on:
      - postgres
    
volumes:
  postgres_data:


networks:
  api-network:
    driver: bridge
    name: api-network
