version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pwd}
      POSTGRES_DB: ${POSTGRES_DB:-pg}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    restart: always
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
